import type { NextPage, GetServerSideProps } from 'next'
import { ProductsData, UserData } from '../components/types';
import Head from 'next/head'
import UserList from '../components/list/UserList';
import fetchData from '../components/fetchData';
import ProductList from '../components/list/ProductsList';

type AppProps = {
  userData: UserData;
  productsData: ProductsData;
}

const Home: NextPage<AppProps> = ({ userData, productsData }) => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <UserList userData={userData} />
        <ProductList productsData={productsData} />
      </main>

      <footer>
      </footer>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  let userFetch = fetchData(process.env.USERURL, "GET", process.env.USERTOKEN)
  let productsFetch = fetchData(process.env.PRODUCTURL, "GET", process.env.USERTOKEN)
  return await Promise.all([userFetch, productsFetch])
    .then(values => {
      let [userData, productsData] = values
      return { props: { userData, productsData } }
    })
}

export default Home
