import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import UserList from '../components/list/UserList';
import styles from '../styles/Home.module.css'

type AppProps = {
  data: Data;
}
interface RedeemHistory {
  productId: string
}
interface Data {
  _id: string;
  name: string;
  points: number;
  createDate: Date;
  redeemHistory: RedeemHistory[];
}

const Home: NextPage<AppProps> = ({ data }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <UserList data={data} />
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  let headers = new Headers()
  headers.append("Content-Type", 'application/json')
  headers.append('Accept', 'application/json')
  headers.append('Authorization', 'Bearer ' + process.env.USERTOKEN)
  const res = await fetch('https://coding-challenge-api.aerolab.co/user/me', { headers })
  const data = await res.json()

  return { props: { data } }
}

export default Home
